name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Added YTHoldForSpeed submodule
        run: |
          git submodule add https://github.com/joshuaseltzer/YTHoldForSpeed Tweaks/YTHoldForSpeed
          git add .
          git commit -m "added YTHoldForSpeed submodule"
          git push origin

      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote
          git add .
          git commit -m "updated submodules"
          git push origin
        continue-on-error: true

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
